name: Feature request
description: Suggest an idea or enhancement.
labels:
  - api
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to propose an improvement.

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to see implemented?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered

  - type: textarea
    id: context
    attributes:
      label: Additional context
