name: Fuzzing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # Nightly

permissions:
  contents: read

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false

      - name: Setup Dart
        uses: dart-lang/setup-dart@65eb853c7ba17dde3be364c3d2858773e7144260

      - name: Install dependencies
        run: dart pub get

      - name: Run Fuzz Tests
        run: dart test fuzz/block_fuzzer.dart
        env:
          FUZZ_ITERATIONS: 5000
